# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoice',
            new_name='MultipleChoiceQuestion',
        ),
        migrations.RenameModel(
            old_name='TrueFalse',
            new_name='TrueFalseQuestion',
        ),
    ]
